name: educonnect
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  syncfusion_flutter_pdfviewer: ^29.2.7
  path_provider: ^2.0.15
  flutter:
    sdk: flutter
  provider: 6.1.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Logo aplikasi (sudah ada)
    - assets/images/LOGO.png
    # File materi PDF (sudah ada)
    - assets/materi/Aljabar.pdf
    - assets/materi/Gerak Lurus Beraturan.pdf
    # Tambahkan progress_icon.png agar bisa dipanggil via Image.asset
    - assets/images/progress_icon.png
